# Custom xv6 (RISC-V) – System Calls, User Utilities, and Scheduler Extensions

This repository contains a customized version of the **xv6 RISC-V operating system** extended with new kernel system calls, Unix-style user-space commands, and CPU scheduling enhancements. The project focuses on understanding low-level OS concepts by implementing features directly inside the kernel and user programs without relying on standard libraries.

---

## 📌 Project Overview

The goal of this project is to extend xv6 in a controlled and educational way, covering:

* Kernel ↔ user-space interaction via system calls
* Safe shared-state access using spinlocks
* File I/O using raw system calls
* Process scheduling policies and benchmarking
* Writing classic Unix utilities from scratch

All features were implemented incrementally and tested inside QEMU.

---

## 🔧 Kernel Enhancements

### Added System Calls

| System Call   | Description                                                                               |
| ------------- | ----------------------------------------------------------------------------------------- |
| `shutdown`    | Performs a clean system shutdown by writing a magic value to the QEMU finisher device     |
| `rand`        | Returns a pseudo-random integer generated by a kernel-level linear congruential generator |
| `uptime`      | Returns the number of timer ticks since the system booted                                 |
| `set_sched`   | Switches the active CPU scheduling policy at runtime                                      |
| `start_bench` | Starts a simple scheduler benchmark run                                                   |

### Scheduler Extensions

* Support for multiple scheduling policies (e.g. Round Robin, FCFS)
* Runtime switching of scheduling policy via system call
* Process runtime tracking (`creation_time`, `run_time`, etc.)
* Optional benchmarking output printed by the kernel

---

## 🧰 User-Space Commands

The following Unix-style commands were implemented in `user/` using xv6 system calls only:

### `diff`

* Compares two files line by line
* Reports differences in content and file length
* Prints a clear message when files are identical

### `cp`

* Copies the contents of one file to another
* Uses buffered reads and handles partial writes correctly
* Creates the destination file if it does not exist

### `wc`

* Enhanced word-count utility
* Supports standard flags:

  * `-l` lines
  * `-w` words
  * `-c` bytes
  * `-m` characters
* Supports multiple files and total aggregation

### `schedtest`

* User program for stressing the CPU scheduler
* Spawns multiple processes to evaluate scheduling behavior

---

## 🏗️ Build & Run

### Build xv6

```bash
make clean
make
```

### Run in QEMU

```bash
make qemu
```

### Example Commands in xv6 Shell

```bash
uptime
rand
diff file1 file2
cp src dst
wc -lwc file
shutdown
```

---

## 🧠 Educational Focus

This project demonstrates:

* How system calls are wired from user space to kernel space
* Safe kernel programming with locks and shared state
* Process scheduling fundamentals
* Implementing Unix utilities without libc
* Debugging kernel-level issues in a minimal OS

---

## 📂 Repository Structure

```
kernel/     # Kernel source (syscalls, scheduler, process management)
user/       # User-space programs and commands
mkfs/       # File system creation tool
Makefile    # Build configuration
README.md   # Project documentation
```

---

## ⚠️ Notes

* This project is **educational** and not intended for production use
* Random number generation is deterministic and not cryptographically secure
* Timing values are measured in kernel ticks, not real-time seconds

---

## 📜 License

Based on MIT xv6 (RISC-V). Used for educational purposes.

---

## ✨ Author

Developed as part of an Operating Systems project to explore kernel internals and Unix-style system design.
